# Generated by Django 5.1.6 on 2025-03-06 14:58

import django.db.models.deletion
import django.utils.timezone
import kanban.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(help_text='Order of column in the board')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.board')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.project')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.column')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.project')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(default=kanban.models.get_ist_time)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='kanban.board')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='kanban.card')),
                ('from_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moved_from', to='kanban.column')),
                ('to_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moved_to', to='kanban.column')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='kanban.project')),
            ],
        ),
        migrations.CreateModel(
            name='CFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_timestamp', models.DateTimeField(default=kanban.models.get_ist_time)),
                ('column_card_counts', models.JSONField(default=dict, help_text='JSON structure of column-wise card counts')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfd_data', to='kanban.board')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfd_data', to='kanban.project')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='kanban.project'),
        ),
    ]
